name: Create SQL Documentation
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: artblck/postgres-plpython3u
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Create plpython3u extension
        run: psql -U postgres -h localhost -d postgres -p 5432 -c 'CREATE EXTENSION IF NOT EXISTS plpython3u'
        env:
          PGPASSWORD: postgres

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create tables and insert data
        run: psql -U postgres -h localhost -d postgres -p 5432 < data/flensburg_sozialatlas.sql
        env:
          PGPASSWORD: postgres

      - name: Generate documentation
        run: python3 generate_documentation.py
        env:
          DB_NAME: postgres
          DB_PASS: postgres
          DB_USER: postgres
          DB_HOST: localhost
          DB_PORT: 5432
