name: Lint javascript files

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'package.json'
      - '.eslintignore'
      - '.eslintrc.yml'
      - '.htmlhintrc'
  pull_request:
      - 'package.json'
      - '.eslintignore'
      - '.eslintrc.yml'
      - '.htmlhintrc'

env:
  NODE_VERSION: 18

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install latest nodejs
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        run: npm ci
        node-version: ${{ env.NODE_VERSION }}

      - name: Install faster package manager
        run: npm ci -g pnpm
        node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies from package.json
        run: pnpm install

      - name: Run lint specified in package.json
        run: pnpm lint:js
